---
title: "Trabajo final"
author: "José Saint Germain"
date: "26/3/2021"
output: html_document
---

```{r}
Pol_en_Tw <- read_html("https://oderedes.shinyapps.io/oder/")

tbls <- html_nodes(Pol_en_Tw, "td") %>% html_text()

Diputados <- as.data.frame(tbls)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Ideas que se me van ocurriendo
##Georreferenciar las persepciones sobre CFK y las palabras que se usan (tanto positivas como negativas)
##Hacer algo de Calvo referido a algún tema actual (Formosa, Chubut, Aborto)
##Comparar palabras usadas entre distintos políticos y dependiendo de su género
#Presencia de una palabra y quién la usa más
#Clusterización de políticos



library(rtweet)
library(tidyverse)
library(data.table)
library(tm)
library(tidytext)
library(tidyverse)
library(igraph)
library(ggplot2)
library(gtable)
library(plotly)
library(wordcloud)
library(reticulate)
```


```{r armar la base}
Tweets_HCSN <- data.frame(matrix(nrow=0,ncol=0))

Senadores <- c("anabelfsagasti","GugaLusto","estebanbullrich","marianorecalde","juliocobos","JorgeTaiana","gladys_gonzalez","mauricloss","JulioMartinezLR","alfredodeangeli","luisnaidenoff","SilviaEdePerez","CarlosMenem_LR","MatiasRodrigTDF","laurmachado","Weretilneck","EduardoCostaSC","claudiojpoggi","MarioFiad","OscarParrilli","SenadorLuenzo","espinolacamau","RomeroxSalta","nancysgonzalez","LupeTagliaferri","JAlperovichOk","sacnun","pilattivergara","PameVerasay","SchiavoniH","giacopposilvia","Juancmarino","dalmaciomera","adolfoRSquotes","Norma_Durango","AnaAlmironCtes","BeatrizMirkinOk","EdgardoKueider","guillermosnopek","RGBasualdo","juanmariopais","CaserioCarlos","SenadoraBlas","eugecatalfamo","mirabellarob","AnaMariaIanni","MaggieSolariQ","ReutemannC","PedroBraillardP","MariabTapia","LucilaCrexell","Oacastillo","Martinez_EF","VZimmermannOK","blancopabloda","ClaudiaLAZamora","Senadora_Olalla","DanielLoveraLP","sapag_silvia","AntonioRodas8","noragimenezok","JoseNederSDE")

for (i in Senadores){
  Base <- get_timeline(i,n=3000)
  
  Tweets_HCSN <- rbind(Tweets_HCSN,Base)
}

save_as_csv(x = Tweets_HCSN,file_name = "Tweets_HCSN",fileEncoding = "UTF-8" )

Base_filtradita <- Tweets_HCSN %>% 
  select(screen_name,text)

save_as_csv(x = Base_filtradita,file_name = "Tweets_HCSN_id_text",fileEncoding = "UTF-8" )

```


```{r}

HCDN <- read_csv("Bases/HCDN_timeline_database.csv")
```


```{r Graf de barras, echo=FALSE}
custom_stop_words <- tm::stopwords("spanish")

custom_stop_words <- custom_stop_words %>% as.data.frame() %>% rename(word=".")

for(i in Politicos){
  
  t <- Tweets_HCSN %>% filter(screen_name==i)
  
  t <- t %>% 
    select(text)%>%
    unnest_tokens(input = text,output = word) 
  
  t <- t %>%  anti_join(custom_stop_words) %>% 
    filter(word!="t.co") %>% 
    filter(word!="https") %>% 
    filter(word!=i) %>%
    filter(word!="http") %>% 
    count(word, sort = TRUE) %>%
    filter(n > 50) %>%
    mutate(word = reorder(word, n))
  
  
  p <- t %>% ggplot(aes(word, n)) +
    geom_col() +
    xlab(NULL) +
    labs(title = i,
         y=NULL)+
    coord_flip()+
    theme_minimal()
  print(p)
}
```

```{r bag of words, echo=FALSE}
custom_stop_words <- tm::stopwords("spanish")

custom_stop_words <- custom_stop_words %>% as.data.frame() %>% rename(word=".")

Sen_bag_word <-  data.frame(matrix(nrow=0,ncol=0))

for(i in Senadores){
  
  t <- Tweets_HCSN %>% filter(screen_name==i)
  
  t <- t %>% 
    select(text)%>%
    unnest_tokens(input = text,output = word) 
  
  t <- t %>%  anti_join(custom_stop_words) %>% 
    filter(word!="t.co") %>% 
    filter(word!="https") %>% 
    filter(word!=i) %>%
    filter(word!="http") %>% 
    count(word, sort = TRUE) %>%
    filter(n > 50) %>%
    mutate(word = reorder(word, n)) %>% 
    mutate(screen_name=i)
  
    Sen_bag_word <- rbind(Sen_bag_word,t)
}

save_as_csv(x = Sen_bag_word,file_name = "Sen_bag_word",fileEncoding = "UTF-8" )
```
